import React,{useEffect,useMemo,useRef,useState} from "react";import * as d3 from "d3";import {Download,Image,Maximize2,RotateCcw} from "lucide-react";
export interface MindNode{id:string;label:string;description:string;nodeType:string;importance:"high"|"medium"|"low";children:MindNode[]}
export interface MindMapContent{root:MindNode;crossLinks:Array<{sourceId:string;targetId:string;label:string}>;highlightNodeIds:string[];misconceptionNodeIds:string[];recommendedSequence:string[]}
export default function MindMapViewer({content,title}:{content:MindMapContent;title:string}){const svgRef=useRef<SVGSVGElement>(null);const [collapsed,setCollapsed]=useState<Set<string>>(new Set());const [selected,setSelected]=useState<MindNode|null>(null);const [fullscreen,setFullscreen]=useState(false);
 const visible=useMemo(()=>{const clone=(n:MindNode):MindNode=>({...n,children:collapsed.has(n.id)?[]:(n.children||[]).map(clone)});return clone(content.root)},[content,collapsed]);
 useEffect(()=>{const svg=svgRef.current;if(!svg)return;const width=1100,height=650;const selection=d3.select(svg);selection.selectAll("*").remove();selection.attr("viewBox",`0 0 ${width} ${height}`);const viewport=selection.append("g");const root=d3.hierarchy(visible);d3.tree<MindNode>().nodeSize([72,220])(root);const nodes=root.descendants();const minX=d3.min(nodes,d=>d.x)??0;nodes.forEach(d=>{d.x=d.x-minX+45;d.y=d.depth*220+60});viewport.selectAll("path.tree-link").data(root.links()).join("path").attr("class","tree-link").attr("d",d3.linkHorizontal<any,any>().x(d=>d.y).y(d=>d.x) as any).attr("fill","none").attr("stroke","#cbd5e1").attr("stroke-width",2);
 const byId=new Map(nodes.map(n=>[n.data.id,n]));viewport.selectAll("path.cross").data(content.crossLinks.filter(l=>byId.has(l.sourceId)&&byId.has(l.targetId))).join("path").attr("d",l=>{const s=byId.get(l.sourceId)!,t=byId.get(l.targetId)!;return`M${s.y},${s.x} Q${(s.y+t.y)/2},${Math.min(s.x,t.x)-35} ${t.y},${t.x}`}).attr("fill","none").attr("stroke","#a78bfa").attr("stroke-dasharray","5 4");
 const node=viewport.selectAll("g.node").data(nodes,d=>(d as any).data.id).join("g").attr("class","node").attr("transform",d=>`translate(${d.y},${d.x})`).style("cursor","pointer").on("click",(_,d)=>{setSelected(d.data);if(d.data.children?.length)setCollapsed(current=>{const next=new Set(current);next.has(d.data.id)?next.delete(d.data.id):next.add(d.data.id);return next})});node.append("rect").attr("x",-8).attr("y",-24).attr("rx",10).attr("width",170).attr("height",48).attr("fill",d=>content.misconceptionNodeIds.includes(d.data.id)?"#fff1f2":content.highlightNodeIds.includes(d.data.id)?"#eff6ff":"#fff").attr("stroke",d=>content.misconceptionNodeIds.includes(d.data.id)?"#fb7185":content.highlightNodeIds.includes(d.data.id)?"#3b82f6":"#cbd5e1").attr("stroke-width",d=>d.data.importance==="high"?2.5:1.5);node.append("text").attr("x",4).attr("y",5).attr("font-size",13).attr("font-family","Microsoft YaHei, sans-serif").attr("font-weight",600).attr("fill","#1e293b").text(d=>d.data.label.slice(0,20));selection.call(d3.zoom<SVGSVGElement,unknown>().scaleExtent([.35,2.5]).on("zoom",e=>viewport.attr("transform",e.transform)));},[visible,content]);
 const reset=()=>{setCollapsed(new Set());setSelected(null);if(svgRef.current)d3.select(svgRef.current).transition().call((d3.zoom<SVGSVGElement,unknown>() as any).transform,d3.zoomIdentity)};
 const svgBlob=()=>{const svg=svgRef.current!;const clone=svg.cloneNode(true) as SVGSVGElement;clone.setAttribute("xmlns","http://www.w3.org/2000/svg");clone.setAttribute("width","1100");clone.setAttribute("height","650");return new Blob([new XMLSerializer().serializeToString(clone)],{type:"image/svg+xml;charset=utf-8"})};
 const download=(blob:Blob,ext:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${title.replace(/[\\/:*?"<>|]/g,"_")}.${ext}`;a.click();URL.revokeObjectURL(a.href)};
 const exportPng=()=>{const blob=svgBlob();const url=URL.createObjectURL(blob);const image=new window.Image();image.onload=()=>{const canvas=document.createElement("canvas");canvas.width=2200;canvas.height=1300;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);canvas.toBlob(p=>p&&download(p,"png"),"image/png");URL.revokeObjectURL(url)};image.src=url};
 return <div className={fullscreen?"fixed inset-0 z-50 bg-white p-4":"space-y-3"}><div className="flex flex-wrap gap-2"><button onClick={reset} className="btn"><RotateCcw className="h-4 w-4"/>重置</button><button onClick={()=>setFullscreen(v=>!v)} className="btn"><Maximize2 className="h-4 w-4"/>全屏</button><button onClick={()=>download(svgBlob(),"svg")} className="btn"><Download className="h-4 w-4"/>SVG</button><button onClick={exportPng} className="btn"><Image className="h-4 w-4"/>PNG</button></div><div className="overflow-auto rounded-xl border bg-slate-50"><svg ref={svgRef} className={fullscreen?"h-[calc(100vh-100px)] min-w-[1100px] w-full":"h-[560px] min-w-[1000px] w-full"}/></div>{selected&&<div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm"><strong>{selected.label}</strong><p className="mt-1 text-slate-600">{selected.description}</p></div>}<div className="text-xs text-slate-500">推荐顺序：{content.recommendedSequence.join(" → ")}</div></div>}
