import React,{useState}from"react";
import{submitLearningResourceQuiz,type LearningResource,type QuizSubmissionResult}from"../../api";

interface QuizQuestion{questionId:string;questionType:string;stem:string;options:string[];scoringPoints:string[];correctAnswer:string;analysis:string;personalizedHint:string;knowledgePoints:string[];difficulty:string}
interface QuizPack{title:string;difficultyDistribution:{foundation:number;intermediate:number;advanced:number};generationBasis:string[];questions:QuizQuestion[];evidenceStatus:string}

export default function QuizPackPreview({resource,content}:{resource:LearningResource;content:QuizPack}){const[answers,setAnswers]=useState<Record<string,number>>({});const[result,setResult]=useState<QuizSubmissionResult|null>(null);const[error,setError]=useState("");const[submitting,setSubmitting]=useState(false);const choiceQuestions=content.questions.filter(item=>item.options.length===4);
 async function submit(){if(choiceQuestions.some(item=>answers[item.questionId]===undefined)){setError("请完成全部选择题后再提交");return}setSubmitting(true);setError("");try{setResult(await submitLearningResourceQuiz({resourceId:resource.id,version:resource.version,subject:resource.subject,answers:choiceQuestions.map(item=>({questionId:item.questionId,answer:String.fromCharCode(65+answers[item.questionId]),durationSeconds:60}))}))}catch(e){setError(e instanceof Error?e.message:"提交失败")}finally{setSubmitting(false)}}
 return <div className="space-y-4"><section className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{content.title}</strong><span className="text-xs text-emerald-700">题库证据：{content.evidenceStatus}</span></div><p className="mt-2 text-xs text-slate-500">难度分布：基础 {content.difficultyDistribution.foundation} · 提高 {content.difficultyDistribution.intermediate} · 综合 {content.difficultyDistribution.advanced}</p></section>
 {content.questions.map((question,index)=><article key={question.questionId} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{index+1}. {question.stem}</h3><span className="text-xs text-slate-500">{question.questionType} · {question.difficulty} · {question.questionId}</span></div>{question.options.length===4?<div className="mt-3 grid gap-2 md:grid-cols-2">{question.options.map((option,optionIndex)=><label key={option} className={`cursor-pointer rounded-lg border p-3 text-sm ${answers[question.questionId]===optionIndex?"border-blue-500 bg-blue-50":""}`}><input className="mr-2" type="radio" name={question.questionId} checked={answers[question.questionId]===optionIndex} onChange={()=>setAnswers(current=>({...current,[question.questionId]:optionIndex}))}/>{String.fromCharCode(65+optionIndex)}. {option}</label>)}</div>:<ul className="mt-3 list-disc pl-5 text-sm text-slate-600">{question.scoringPoints.map(point=><li key={point}>{point}</li>)}</ul>}<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm">个性化提示：{question.personalizedHint}</p><details className="mt-2 text-sm"><summary className="cursor-pointer font-semibold">查看答案与解析</summary><p className="mt-2">答案：{question.correctAnswer}</p><p className="mt-1 text-slate-600">{question.analysis}</p></details></article>)}
 {choiceQuestions.length>0&&<div className="flex items-center gap-3"><button disabled={submitting} onClick={()=>void submit()} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{submitting?"提交中…":"进入现有测验提交能力"}</button>{result&&<span className="text-sm font-semibold text-emerald-700">得分 {result.score}，答对 {result.correctCount}/{result.totalCount}</span>}</div>}{error&&<p className="text-sm text-rose-600">{error}</p>}</div>}
