const fs=require("fs/promises"); const PptxGenJS=require("pptxgenjs"); const JSZip=require("jszip");
const MIME="application/vnd.openxmlformats-officedocument.presentationml.presentation";
async function generatePptx(content,filePath){const pptx=new PptxGenJS();pptx.layout="LAYOUT_WIDE";pptx.author="LearnMate";pptx.subject="个性化学习课件";pptx.title=content.slides[0].title;pptx.company="LearnMate";pptx.lang="zh-CN";pptx.theme={headFontFace:"Microsoft YaHei",bodyFontFace:"Microsoft YaHei",lang:"zh-CN"};
  content.slides.forEach((slide,index)=>renderSlide(pptx,slide,index));await pptx.writeFile({fileName:filePath});await validatePptxFile(filePath);return filePath;}
function renderSlide(pptx,data,index){const slide=pptx.addSlide();slide.background={color:index===0?"EFF6FF":"FFFFFF"};slide.addText(data.title,{x:.65,y:.45,w:12,h:.55,fontFace:"Microsoft YaHei",fontSize:index===0?28:24,bold:true,color:"153B70",margin:0});let y=1.3;
  if(data.subtitle){slide.addText(data.subtitle,{x:.75,y,w:11.7,h:.5,fontSize:16,color:"475569"});y+=.7;} if(data.body){slide.addText(data.body,{x:.8,y,w:11.6,h:1.5,fontSize:17,color:"334155",breakLine:true,fit:"shrink"});y+=1.7;}
  const bullets=data.bullets||data.nextSteps;if(bullets?.length){slide.addText(bullets.map((t)=>({text:String(t),options:{bullet:{indent:18},breakLine:true}})),{x:.9,y,w:11.2,h:4.8,fontSize:18,color:"1E293B",breakLine:true,fit:"shrink",paraSpaceAfterPt:10});}
  if(data.steps?.length){data.steps.slice(0,6).forEach((s,i)=>{slide.addShape(pptx.ShapeType.roundRect,{x:.8,y:y+i*.75,w:11.4,h:.58,fill:{color:i%2?"F8FAFC":"EFF6FF"},line:{color:"BFDBFE"},radius:.08});slide.addText(`${i+1}. ${s.title} — ${s.description}`,{x:1,y:y+.12+i*.75,w:11,h:.3,fontSize:15,color:"1E293B",fit:"shrink"});});}
  if(data.items?.length){slide.addText(data.items.map((it)=>typeof it==="string"?it:`错误：${it.mistake||it.title}\n纠正：${it.correction||it.description}`).join("\n\n"),{x:.8,y,w:11.5,h:4.7,fontSize:17,color:"7F1D1D",fit:"shrink"});}
  if(data.code){slide.addText(data.code,{x:.8,y,w:11.5,h:3.6,fontFace:"Consolas",fontSize:14,color:"E2E8F0",fill:{color:"0F172A"},margin:.2,fit:"shrink"});if(data.explanation)slide.addText(data.explanation,{x:.8,y:y+3.8,w:11.5,h:.6,fontSize:14,color:"475569",fit:"shrink"});}
  if(data.questionIds?.length)slide.addText(data.questionIds.map((id)=>`• ${id}`).join("\n"),{x:.9,y,w:11,h:3,fontSize:20,color:"1E293B"});
  if(data.left&&data.right){for(const [i,part] of [data.left,data.right].entries()){slide.addText(part.title,{x:.8+i*6,y,w:5.5,h:.45,fontSize:19,bold:true,color:"1D4ED8"});slide.addText(part.items.join("\n"),{x:.8+i*6,y:y+.55,w:5.4,h:3.5,fontSize:16,fit:"shrink"});}}
  slide.addText(`LearnMate · ${index+1}`,{x:11.5,y:7.1,w:1.2,h:.2,fontSize:9,color:"94A3B8",align:"right"});if(data.speakerNotes)slide.addNotes(data.speakerNotes);}
async function validatePptxFile(filePath){const bytes=await fs.readFile(filePath);if(bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error("PPTX is not a ZIP package");const zip=await JSZip.loadAsync(bytes);for(const name of ["[Content_Types].xml","ppt/presentation.xml","ppt/slides/slide1.xml"])if(!zip.file(name))throw new Error(`PPTX missing ${name}`);return{size:bytes.length,entries:Object.keys(zip.files)};}
module.exports={generatePptx,validatePptxFile,MIME};
