const fs=require("fs/promises"); const crypto=require("crypto"); const {pool}=require("../config/db");
const {buildResourceContext}=require("./resourceContextService"); const {validateResourceEnvelope,fingerprint}=require("./resourceSchema");
const {generateStructuredResource}=require("./agents/multimodalResourceAgent"); const {reviewStructuredResource}=require("./agents/multimodalReviewAgent");
const {generatePptx,MIME}=require("./pptxService"); const storage=require("./resourceStorageService");
const {groundResource}=require("./groundedResourceService"); const {persistCitations}=require("./citationValidationService");
const PROMPT_VERSION="resource-grounded-v2";

async function generateResource(input){const context=await buildResourceContext(input);const contextFingerprint=fingerprint({studentId:context.studentId,resourceType:context.resourceType,subject:context.subject,knowledgePoint:context.knowledgePoint,pathVersion:context.pathVersion,stageKey:context.stageKey,stageGoals:context.stageGoals,masteryBucket:Math.floor(context.mastery/10)*10,errorPatterns:context.errorPatterns.map((e)=>e.errorType),explanationPreference:context.explanationPreference,resourcePreferences:context.resourcePreferences,estimatedMinutes:context.estimatedMinutes,promptVersion:PROMPT_VERSION});
  const connection=await pool.getConnection();let lockName;let tempPath;let finalizedPath;
  try{lockName=`learnmate-resource-${context.studentId}-${context.resourceType}-${context.pathVersion}-${context.stageKey}`;const [[lock]]=await connection.query("SELECT GET_LOCK(?,15) AS acquired",[lockName]);if(!lock.acquired)throw apiError("resource generation is busy",409);
    await connection.beginTransaction();await connection.query(`INSERT INTO learning_resources (student_id,subject,knowledge_point,resource_type,title,status,current_version,context_fingerprint,source_type,path_version,stage_key,estimated_minutes) VALUES (?,?,?,?,?,'generating',0,?,'agent',?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)`,[context.studentId,context.subject,context.knowledgePoint,context.resourceType,`${context.knowledgePoint}学习资源`,contextFingerprint,context.pathVersion,context.stageKey,context.estimatedMinutes]);
    const resourceId=Number((await connection.query("SELECT LAST_INSERT_ID() AS id"))[0][0].id)||Number((await connection.query("SELECT id FROM learning_resources WHERE student_id=? AND resource_type=? AND path_version=? AND stage_key=? FOR UPDATE",[context.studentId,context.resourceType,context.pathVersion,context.stageKey]))[0][0].id);
    const [[resource]]=await connection.query("SELECT * FROM learning_resources WHERE id=? FOR UPDATE",[resourceId]);
    if(!input.regenerate&&resource.status==="approved"&&resource.context_fingerprint===contextFingerprint){await connection.commit();return getResource(context.studentId,resourceId);}
    await connection.query("UPDATE learning_resources SET status='generating',context_fingerprint=?,error_summary=NULL WHERE id=?",[contextFingerprint,resourceId]);await connection.commit();
    const generated=await generateStructuredResource(context);let content=validateResourceEnvelope(generated.content,context);const grounding=context.subject==="数据结构"?await groundResource(pool,content,context):null;if(grounding)content=validateResourceEnvelope(grounding.envelope,context);const review=await reviewStructuredResource(content,context);content=applyReview(content,review,context);const contentFingerprint=resourceFingerprint(content);
    const [[latest]]=await connection.query("SELECT current_version,content_fingerprint FROM learning_resources WHERE id=?",[resourceId]);if(latest.current_version>0&&latest.content_fingerprint===contentFingerprint){await connection.query("UPDATE learning_resources SET status='approved',error_summary=NULL WHERE id=?",[resourceId]);return getResource(context.studentId,resourceId);}
    const nextVersion=Number(latest.current_version)+1;let fileMeta=null;if(context.resourceType==="pptx"){tempPath=await storage.prepareTempFile("pptx");await generatePptx(content.content,tempPath,content.citations);}
    await connection.beginTransaction();await connection.query("SELECT id FROM learning_resources WHERE id=? FOR UPDATE",[resourceId]);await connection.query(`INSERT INTO learning_resource_versions (resource_id,student_id,version,content_json,review_json,content_fingerprint,generator_source,model_name,prompt_version,retrieval_run_id,citations_json) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,[resourceId,context.studentId,nextVersion,JSON.stringify(content),JSON.stringify(review),contentFingerprint,generated.source,generated.model,PROMPT_VERSION,grounding?.retrieval.retrievalRunId||null,JSON.stringify(content.citations||[])]);if(grounding)await persistCitations(connection,{studentId:context.studentId,generationType:context.resourceType,generationId:String(resourceId),generationVersion:nextVersion,validation:grounding.validation});
    if(tempPath){fileMeta=await storage.finalizeFile(tempPath,{studentId:context.studentId,resourceId,version:nextVersion,fileType:"pptx"});tempPath=null;finalizedPath=fileMeta.absolutePath;await connection.query(`INSERT INTO learning_resource_files (resource_id,resource_version,student_id,file_type,storage_path,original_filename,mime_type,file_size,checksum_sha256) VALUES (?,?,?,'pptx',?,?,?,?,?)`,[resourceId,nextVersion,context.studentId,fileMeta.storagePath,safeDownloadName(content.title,"pptx"),MIME,fileMeta.fileSize,fileMeta.checksum]);}
    await connection.query(`INSERT INTO learning_resource_stage_links (student_id,resource_id,resource_version,path_version,stage_key) VALUES (?,?,?,?,?)`,[context.studentId,resourceId,nextVersion,context.pathVersion,context.stageKey]);await connection.query(`INSERT INTO learning_resource_progress (student_id,resource_id,resource_version,status,progress_percent) VALUES (?,?,?,'not_started',0)`,[context.studentId,resourceId,nextVersion]);await connection.query(`UPDATE learning_resources SET title=?,status='approved',current_version=?,content_fingerprint=?,estimated_minutes=? WHERE id=?`,[content.title,nextVersion,contentFingerprint,content.estimatedMinutes,resourceId]);await connection.commit();finalizedPath=null;return getResource(context.studentId,resourceId);
  }catch(error){await connection.rollback().catch(()=>undefined);if(input.studentId)await pool.query("UPDATE learning_resources SET status=IF(current_version>0,'approved','failed'),error_summary=? WHERE student_id=? AND resource_type=? AND path_version=? AND stage_key=?",[String(error.message).slice(0,255),input.studentId,input.resourceType,input.pathVersion,input.stageKey]).catch(()=>undefined);await storage.cleanupFile(tempPath);await storage.cleanupFile(finalizedPath);throw error;}finally{if(lockName)await connection.query("SELECT RELEASE_LOCK(?)",[lockName]).catch(()=>undefined);connection.release();}}

async function listResources(studentId,filters={}){const where=["student_id=?"],params=[studentId];for(const [field,column] of [["resourceType","resource_type"],["subject","subject"],["knowledgePoint","knowledge_point"],["stageKey","stage_key"],["status","status"]])if(filters[field]){where.push(`${column}=?`);params.push(String(filters[field]));}const limit=Math.max(1,Math.min(100,Number(filters.limit)||30));const [rows]=await pool.query(`SELECT id FROM learning_resources WHERE ${where.join(" AND ")} ORDER BY updated_at DESC LIMIT ${limit}`,params);return Promise.all(rows.map((row)=>getResource(studentId,row.id)));}
async function getResource(studentId,resourceId,version=null){const [[r]]=await pool.query("SELECT * FROM learning_resources WHERE id=? AND student_id=? LIMIT 1",[resourceId,studentId]);if(!r)throw apiError("resource not found",404);const selected=version?Number(version):Number(r.current_version);const [[v]]=await pool.query("SELECT * FROM learning_resource_versions WHERE resource_id=? AND student_id=? AND version=? LIMIT 1",[r.id,studentId,selected]);if(!v)throw apiError("resource version not found",404);const [[p]]=await pool.query("SELECT * FROM learning_resource_progress WHERE student_id=? AND resource_id=? AND resource_version=?",[studentId,r.id,selected]);return toPublic(r,v,p);}
async function listVersions(studentId,resourceId){await assertOwner(studentId,resourceId);const [rows]=await pool.query("SELECT version,review_json,content_fingerprint,generator_source,model_name,prompt_version,created_at FROM learning_resource_versions WHERE resource_id=? AND student_id=? ORDER BY version DESC",[resourceId,studentId]);return rows.map((r)=>({...r,review:parse(r.review_json)}));}
async function getDownload(studentId,resourceId,version=null){const resource=await getResource(studentId,resourceId,version);const [[file]]=await pool.query("SELECT * FROM learning_resource_files WHERE resource_id=? AND student_id=? AND resource_version=? AND file_type='pptx'",[resourceId,studentId,resource.version]);if(!file)throw apiError("download not available",404);await pool.query("UPDATE learning_resource_progress SET downloaded_at=NOW(),last_activity_at=NOW(),status=IF(status='not_started','opened',status) WHERE student_id=? AND resource_id=? AND resource_version=?",[studentId,resourceId,resource.version]);return{...file,absolutePath:storage.resolveStoredFile(file.storage_path)};}
async function openResource(studentId,resourceId){const r=await getResource(studentId,resourceId);await pool.query("UPDATE learning_resource_progress SET opened_at=COALESCE(opened_at,NOW()),last_activity_at=NOW(),status=IF(status='not_started','opened',status) WHERE student_id=? AND resource_id=? AND resource_version=?",[studentId,resourceId,r.version]);return getResource(studentId,resourceId);}
async function updateProgress(studentId,resourceId,{progressPercent}){const r=await getResource(studentId,resourceId);const percent=Math.max(0,Math.min(100,Math.round(Number(progressPercent)||0)));await pool.query("UPDATE learning_resource_progress SET progress_percent=GREATEST(progress_percent,?),accumulated_seconds=accumulated_seconds+LEAST(60,GREATEST(0,TIMESTAMPDIFF(SECOND,last_activity_at,NOW()))),last_activity_at=NOW(),status=IF(?=100,'in_progress',IF(status='not_started','opened',status)) WHERE student_id=? AND resource_id=? AND resource_version=?",[percent,percent,studentId,resourceId,r.version]);return getResource(studentId,resourceId);}
async function completeResource(studentId,resourceId){const r=await getResource(studentId,resourceId);const [[p]]=await pool.query("SELECT * FROM learning_resource_progress WHERE student_id=? AND resource_id=? AND resource_version=?",[studentId,resourceId,r.version]);const accessOk=Boolean(p.opened_at)||(r.resourceType==="pptx"&&p.downloaded_at);if(!accessOk||Number(p.progress_percent)<100||Number(p.accumulated_seconds)<30)throw apiError("completion requirements not met",422);await pool.query("UPDATE learning_resource_progress SET status='completed',completed_at=NOW(),last_activity_at=NOW(),evidence_json=? WHERE id=?",[JSON.stringify({openedAt:p.opened_at,downloadedAt:p.downloaded_at,progressPercent:p.progress_percent,accumulatedSeconds:p.accumulated_seconds}),p.id]);return getResource(studentId,resourceId);}
async function stageResources(studentId,pathVersion,stageKey){return listResources(studentId,{stageKey,status:"approved",limit:50}).then((items)=>items.filter((x)=>x.pathVersion===Number(pathVersion)));}
async function assertOwner(studentId,id){const [[r]]=await pool.query("SELECT id FROM learning_resources WHERE id=? AND student_id=?",[id,studentId]);if(!r)throw apiError("resource not found",404);}
function toPublic(r,v,p){const content=parse(v.content_json),review=parse(v.review_json);return{id:Number(r.id),version:Number(v.version),resourceType:r.resource_type,title:r.title,status:r.status,subject:r.subject,knowledgePoint:r.knowledge_point,stageKey:r.stage_key,pathVersion:Number(r.path_version),estimatedMinutes:Number(r.estimated_minutes),generationRationale:content.generationRationale||[],content:content.content,retrievalRunId:Number(v.retrieval_run_id||content.retrievalRunId)||null,citations:parse(v.citations_json).length?parse(v.citations_json):content.citations||[],learningObjectives:content.learningObjectives||[],targetLearnerSummary:content.targetLearnerSummary,review,progress:p?{status:p.status,progressPercent:Number(p.progress_percent),accumulatedSeconds:Number(p.accumulated_seconds),openedAt:p.opened_at,completedAt:p.completed_at,downloadedAt:p.downloaded_at}:null,createdAt:v.created_at};}
function applyReview(content,review,context){if(review.status==="rejected")throw apiError("resource rejected by review",422);const corrected=review.status==="needs_revision"&&review.correctedContent?review.correctedContent:content;return validateResourceEnvelope(corrected,context);}
function parse(v){if(v&&typeof v==="object")return v;try{return JSON.parse(v||"{}");}catch{return {};}}function resourceFingerprint(content){return fingerprint({...content,retrievalRunId:undefined,citations:(content.citations||[]).map(({supportScore,...citation})=>citation)});}function safeDownloadName(title,ext){return`${String(title).replace(/[\\/:*?"<>|\r\n]/g,"_").slice(0,80)||"LearnMate"}.${ext}`;}function apiError(message,statusCode){const e=new Error(message);e.statusCode=statusCode;return e;}
module.exports={generateResource,listResources,getResource,listVersions,getDownload,openResource,updateProgress,completeResource,stageResources,applyReview};
