const { pool } = require("../config/db");
const { retrieveKnowledge } = require("../services/knowledgeRetrievalService");
const { generateGroundedAnswer } = require("../services/groundedAnswerService");
async function search(req, res, next) { try { return res.json(await retrieveKnowledge(pool, { ...req.body, studentId: req.user.studentId, requestType: req.body.requestType || "chat" })); } catch (error) { return next(error); } }
async function answer(req, res, next) { try { return res.json(await generateGroundedAnswer(pool, { ...req.body, studentId: req.user.studentId })); } catch (error) { return next(error); } }
async function run(req, res, next) { try { const [[row]] = await pool.query("SELECT * FROM knowledge_retrieval_runs WHERE id=? AND student_id=?", [Number(req.params.id), req.user.studentId]); if (!row) return res.status(404).json({ error: "not found" }); const [results] = await pool.query("SELECT * FROM knowledge_retrieval_results WHERE retrieval_run_id=? ORDER BY rank_position", [row.id]); return res.json({ ...row, results }); } catch (error) { return next(error); } }
async function sources(req, res, next) { try { const [rows] = await pool.query("SELECT source_key,title,author,publisher,license_name,source_type,subject,language,version,status,quality_grade,imported_at FROM knowledge_sources WHERE status='active' ORDER BY title,version"); return res.json({ sources: rows }); } catch (error) { return next(error); } }
async function citations(req, res, next) { try { const [rows] = await pool.query("SELECT generation_type,generation_id,generation_version,location_key,claim_text,chunk_id,citation_label,support_score,validation_status,source_snapshot_json,created_at FROM generation_citations WHERE student_id=? AND generation_type=? AND generation_id=? AND generation_version=? ORDER BY location_key,citation_label", [req.user.studentId, req.params.generationType, req.params.generationId, Number(req.params.version)]); if (!rows.length) return res.status(404).json({ error: "not found" }); return res.json({ citations: rows.map((row) => ({ ...row, sourceSnapshot: typeof row.source_snapshot_json === "string" ? JSON.parse(row.source_snapshot_json) : row.source_snapshot_json })) }); } catch (error) { return next(error); } }
module.exports = { search, answer, run, sources, citations };
