const express=require("express");
const {authMiddleware,requireRole}=require("../middleware/authMiddleware");
const c=require("../controllers/teacherController");
const router=express.Router();
router.use(authMiddleware,requireRole("TEACHER","ADMIN"));
router.get("/teacher/dashboard/overview",c.dashboard);
router.get("/teacher/dashboard/trends",c.trends);
router.get("/teacher/classes",c.classes);
router.get("/teacher/classes/:classId/analytics",c.classAnalytics);
router.get("/teacher/students",c.students);
router.get("/teacher/students/:studentId/detail",c.studentDetail);
router.get("/teacher/students/:studentId/profile-history",c.profileHistory);
router.get("/teacher/students/:studentId/mastery",c.mastery);
router.get("/teacher/students/:studentId/quiz-trend",c.quizTrend);
router.get("/teacher/students/:studentId/path",c.path);
router.get("/teacher/students/:studentId/resources",c.studentResources);
router.get("/teacher/students/:studentId/retrieval-activity",c.retrievalActivity);
router.post("/teacher/students/:studentId/resources/generate",c.generateStudentResource);
router.get("/teacher/quiz-analytics",c.quizAnalytics);
router.get("/teacher/agent-logs",c.agentLogs);
router.post("/teacher/students/:studentId/reports",c.createReport);
router.get("/teacher/reports",c.listReports);
router.get("/teacher/reports/:reportId",c.reportDetail);
router.get("/teacher/reports/:reportId/download",c.reportDownload);
module.exports=router;
