import React,{useEffect,useMemo,useState}from"react";import{BookOpen,Download,FileText,Loader2,Network,RefreshCw,Sparkles}from"lucide-react";
import{completeLearningResource,downloadLearningResource,generateLearningResource,getLearningPath,getLearningResource,getResourceVersions,listLearningResources,openLearningResource,updateLearningResourceProgress,type LearningResource}from"../api";import type{LearningPathResponse,PathStage}from"../types";import ResourcePreview from"./resources/ResourcePreview";
interface Props{onNavigateToTab:(tab:string,prefill?:unknown)=>void;initialRecommendation?:{resourceType?:string;title?:string;reason?:string;knowledgePointId?:string;subject?:string;stageKey?:string;pathVersion?:number}|null}
export default function ResourceView({initialRecommendation}:Props){const[path,setPath]=useState<LearningPathResponse|null>(null);const[stage,setStage]=useState<PathStage|null>(null);const[resources,setResources]=useState<LearningResource[]>([]);const[selected,setSelected]=useState<LearningResource|null>(null);const[versions,setVersions]=useState<Array<Record<string,unknown>>>([]);const[state,setState]=useState<"loading"|"idle"|"generating"|"ready"|"failed">("loading");const[error,setError]=useState("");
 const context=useMemo(()=>stage&&path?{subject:stage.subject,knowledgePoint:stage.knowledgePoints[0],stageKey:stage.key,pathVersion:path.version}:null,[stage,path]);
 useEffect(()=>{void(async()=>{try{const p=await getLearningPath();setPath(p);const chosen=p.stages.find(s=>s.key===initialRecommendation?.stageKey)||p.stages.find(s=>s.status==="active")||p.stages[0];setStage(chosen||null);setState("idle");}catch(e){setError(e instanceof Error?e.message:"路径读取失败");setState("failed")}})()},[initialRecommendation?.stageKey]);
 useEffect(()=>{if(!context)return;void loadList()},[context?.stageKey,context?.pathVersion]);
 async function loadList(){if(!context)return;try{const list=await listLearningResources({stageKey:context.stageKey,status:"approved"});const filtered=list.filter(r=>r.pathVersion===context.pathVersion);setResources(filtered);if(filtered[0])await selectResource(filtered[0]);}catch(e){setError(e instanceof Error?e.message:"资源列表加载失败")}}
 async function selectResource(resource:LearningResource){try{const opened=await openLearningResource(resource.id);setSelected(opened);setVersions(await getResourceVersions(resource.id));setState("ready")}catch(e){setError(e instanceof Error?e.message:"资源打开失败")}}
 async function generate(resourceType:"mind_map"|"pptx",regenerate=false){if(!context)return;setState("generating");setError("");try{const result=await generateLearningResource({...context,resourceType,regenerate});await loadList();await selectResource(result)}catch(e){setError(e instanceof Error?e.message:"生成失败");setState("failed")}}
 async function markComplete(){if(!selected)return;try{const progressed=await updateLearningResourceProgress(selected.id,100);setSelected(progressed);const completed=await completeLearningResource(selected.id);setSelected(completed);await loadList()}catch(e){setError(e instanceof Error?e.message:"需打开并阅读至少 30 秒后才能完成")}}
 if(state==="loading")return<div className="flex min-h-72 items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>读取路径资源…</div>;
 return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><span className="text-xs font-semibold text-blue-600">当前真实路径阶段</span><h2 className="mt-1 text-xl font-bold">{stage?.title||"暂无可用阶段"}</h2><p className="mt-1 text-sm text-slate-500">V{path?.version} · {context?.subject} / {context?.knowledgePoint}</p></div><div className="flex flex-wrap gap-2"><button disabled={!context||state==="generating"}onClick={()=>generate("mind_map")}className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Network className="h-4 w-4"/>生成思维导图</button><button disabled={!context||state==="generating"}onClick={()=>generate("pptx")}className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><FileText className="h-4 w-4"/>生成个性化课件</button></div></div>{state==="generating"&&<p className="mt-4 flex items-center text-sm text-blue-600"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>后端正在真实生成、审核并保存资源…</p>}{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}</section>
 <div className="grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-bold">阶段资源</h3><button onClick={()=>void loadList()}><RefreshCw className="h-4 w-4"/></button></div>{resources.length===0?<div className="py-10 text-center text-xs text-slate-400"><BookOpen className="mx-auto mb-2 h-8 w-8"/>尚未生成资源</div>:<div className="mt-3 space-y-2">{resources.map(r=><button key={r.id}onClick={()=>void selectResource(r)}className={`w-full rounded-xl border p-3 text-left text-xs ${selected?.id===r.id?"border-blue-400 bg-blue-50":"border-slate-100"}`}><strong>{r.title}</strong><div className="mt-1 text-slate-400">{r.resourceType} · V{r.version} · {r.review.score}分</div><div className="mt-1 text-slate-500">进度 {r.progress?.progressPercent||0}%</div></button>)}</div>}</aside>
 <main className="min-h-[560px] rounded-2xl border bg-white p-5 shadow-sm">{selected?<><div className="mb-4 flex flex-wrap justify-end gap-2">{selected.resourceType==="pptx"&&<button onClick={()=>void downloadLearningResource(selected.id,selected.version)}className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold"><Download className="h-4 w-4"/>下载 PPTX</button>}<button onClick={()=>void generate(selected.resourceType,true)}className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold"><Sparkles className="h-4 w-4"/>重新生成</button><button onClick={()=>void markComplete()}className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">完成学习</button></div><ResourcePreview resource={selected}/><div className="mt-5"><h3 className="text-sm font-bold">版本历史</h3><div className="mt-2 flex flex-wrap gap-2">{versions.map(v=><button key={String(v.version)}onClick={()=>void getLearningResource(selected.id,Number(v.version)).then(setSelected)}className="rounded-lg bg-slate-100 px-2 py-1 text-xs">V{String(v.version)} · {String((v.review as any)?.score||"")}分</button>)}</div></div></>:<div className="flex h-full items-center justify-center text-sm text-slate-400">选择或生成一个真实资源</div>}</main></div></div>}
