import React,{useEffect,useMemo,useState}from"react";
import{BookOpen,Braces,Download,FileQuestion,FileText,Loader2,Network,NotebookText,RefreshCw,Sparkles}from"lucide-react";
import{completeLearningResource,downloadLearningResource,generateLearningResource,getLearningPath,getLearningResource,getResourceVersions,listLearningResources,openLearningResource,updateLearningResourceProgress,type LearningResource,type LearningResourceType}from"../api";
import type{LearningPathResponse,PathStage}from"../types";
import ResourcePreview from"./resources/ResourcePreview";

interface Props{onNavigateToTab:(tab:string,prefill?:unknown)=>void;initialRecommendation?:{resourceType?:string;title?:string;reason?:string;knowledgePointId?:string;subject?:string;stageKey?:string;pathVersion?:number}|null}
type PageState="loading"|"empty"|"generating"|"success"|"partial"|"error";
const TYPES:Array<{type:LearningResourceType;name:string;description:string;icon:React.ComponentType<{className?:string}>}>=[
 {type:"study_note",name:"个性化学习讲义",description:"结合掌握度、错误模式与讲解偏好的结构化讲义",icon:NotebookText},
 {type:"mind_map",name:"个性化思维导图",description:"可折叠、缩放、高亮并导出的知识结构",icon:Network},
 {type:"pptx",name:"个性化课件",description:"真实生成、校验、下载并保留版本的 PPTX",icon:FileText},
 {type:"quiz_pack",name:"自适应练习包",description:"只引用真实题库 ID，并可提交到现有测验流程",icon:FileQuestion},
 {type:"code_case",name:"代码实操案例",description:"复用 CodeLab 练习并区分已验证与生成代码",icon:Braces}
];

export default function ResourceView({onNavigateToTab,initialRecommendation}:Props){
 const[path,setPath]=useState<LearningPathResponse|null>(null);const[stage,setStage]=useState<PathStage|null>(null);const[resources,setResources]=useState<LearningResource[]>([]);const[selected,setSelected]=useState<LearningResource|null>(null);const[versions,setVersions]=useState<Array<Record<string,unknown>>>([]);const[state,setState]=useState<PageState>("loading");const[generatingType,setGeneratingType]=useState<LearningResourceType|null>(null);const[failedType,setFailedType]=useState<LearningResourceType|null>(null);const[error,setError]=useState("");
 const context=useMemo(()=>stage&&path?{subject:stage.subject,knowledgePoint:stage.knowledgePoints[0],stageKey:stage.key,pathVersion:path.version}:null,[stage,path]);
 useEffect(()=>{void(async()=>{try{const p=await getLearningPath();setPath(p);const chosen=p.stages.find(s=>s.key===initialRecommendation?.stageKey)||p.stages.find(s=>s.status==="active")||p.stages[0];setStage(chosen||null);setState(chosen?"empty":"partial")}catch(e){setError(e instanceof Error?e.message:"路径读取失败");setState("error")}})()},[initialRecommendation?.stageKey]);
 useEffect(()=>{if(context)void loadList()},[context?.stageKey,context?.pathVersion]);
 async function loadList(preferredId?:number){if(!context)return;try{const list=await listLearningResources({stageKey:context.stageKey,status:"approved"});const filtered=list.filter(r=>r.pathVersion===context.pathVersion);setResources(filtered);const preferred=filtered.find(item=>item.id===preferredId)||filtered.find(item=>item.resourceType===initialRecommendation?.resourceType)||filtered[0];if(preferred)await selectResource(preferred);else{setSelected(null);setVersions([]);setState("empty")}}catch(e){setError(e instanceof Error?e.message:"资源列表加载失败");setState("error")}}
 async function selectResource(resource:LearningResource){try{const opened=await openLearningResource(resource.id);setSelected(opened);setVersions(await getResourceVersions(resource.id));setState(opened.review.status==="approved"?"success":"partial")}catch(e){setError(e instanceof Error?e.message:"资源打开失败");setState("error")}}
 async function generate(resourceType:LearningResourceType,regenerate=false){if(!context)return;setGeneratingType(resourceType);setFailedType(null);setState("generating");setError("");try{const result=await generateLearningResource({...context,resourceType,regenerate});await loadList(result.id);await selectResource(result)}catch(e){setFailedType(resourceType);setError(e instanceof Error?e.message:"生成失败");setState("error")}finally{setGeneratingType(null)}}
 async function markComplete(){if(!selected)return;try{const progressed=await updateLearningResourceProgress(selected.id,100);setSelected(progressed);const completed=await completeLearningResource(selected.id);setSelected(completed);setResources(current=>current.map(item=>item.id===completed.id?completed:item));setState(completed.progress?.status==="completed_unverified"?"partial":"success")}catch(e){setError(e instanceof Error?e.message:"需打开并阅读至少 30 秒后才能完成");setState("partial")}}
 function typeStatus(type:LearningResourceType){if(generatingType===type)return"generating";if(failedType===type)return"error";const item=resources.find(resource=>resource.resourceType===type);if(!item)return"empty";return item.review.status==="approved"?"success":"partial"}
 if(state==="loading")return<div className="flex min-h-72 items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>读取路径资源…</div>;
 return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><span className="text-xs font-semibold text-blue-600">当前真实路径阶段</span><h2 className="mt-1 text-xl font-bold">{stage?.title||"暂无可用阶段"}</h2><p className="mt-1 text-sm text-slate-500">V{path?.version} · {context?.subject} / {context?.knowledgePoint}</p></div><button onClick={()=>void loadList()} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border px-3 text-sm"><RefreshCw className="h-4 w-4"/>刷新</button></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{TYPES.map(({type,name,description,icon:Icon})=>{const status=typeStatus(type);const exists=resources.some(item=>item.resourceType===type);return <article key={type} className="flex min-h-48 flex-col rounded-xl border p-4"><div className="flex items-start justify-between gap-2"><Icon className="h-5 w-5 text-blue-600"/><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${status==="success"?"bg-emerald-50 text-emerald-700":status==="error"?"bg-rose-50 text-rose-700":status==="partial"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{status}</span></div><h3 className="mt-3 text-sm font-bold">{name}</h3><p className="mt-1 flex-1 text-xs leading-5 text-slate-500">{description}</p><button disabled={!context||generatingType!==null} onClick={()=>void generate(type,exists)} className="mt-3 inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">{status==="generating"?<Loader2 className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}{exists?"重新生成":"生成"}</button></article>})}</div>
 {state==="generating"&&<p className="mt-4 flex items-center text-sm text-blue-600"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>后端正在读取画像、生成结构、审核并持久化版本…</p>}{error&&<div className="mt-4 flex flex-wrap items-center gap-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700"><span>{error}</span>{failedType&&<button onClick={()=>void generate(failedType)} className="rounded-lg border border-rose-200 bg-white px-3 py-1 font-semibold">重试</button>}</div>}</section>
 <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="rounded-2xl border bg-white p-4 shadow-sm"><h3 className="font-bold">阶段资源</h3>{resources.length===0?<div className="py-10 text-center text-xs text-slate-400"><BookOpen className="mx-auto mb-2 h-8 w-8"/>尚未生成资源，不使用 Mock 内容填充</div>:<div className="mt-3 space-y-2">{resources.map(r=><button key={r.id} onClick={()=>void selectResource(r)} className={`w-full rounded-xl border p-3 text-left text-xs ${selected?.id===r.id?"border-blue-400 bg-blue-50":"border-slate-100"}`}><strong>{TYPES.find(item=>item.type===r.resourceType)?.name||r.title}</strong><div className="mt-1 text-slate-500">{r.title}</div><div className="mt-1 text-slate-400">V{r.version} · 审核 {r.review.score}分</div><div className="mt-1 text-slate-500">进度 {r.progress?.progressPercent||0}% · {r.progress?.status}</div></button>)}</div>}</aside>
 <main className="min-h-[560px] rounded-2xl border bg-white p-4 shadow-sm md:p-5">{selected?<><div className="mb-4 flex flex-wrap justify-end gap-2">{selected.resourceType==="pptx"&&<button onClick={()=>void downloadLearningResource(selected.id,selected.version)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold"><Download className="h-4 w-4"/>下载 PPTX</button>}<button onClick={()=>void generate(selected.resourceType,true)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold"><Sparkles className="h-4 w-4"/>重新生成</button><button onClick={()=>void markComplete()} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">完成学习</button></div><ResourcePreview resource={selected} onOpenCodeLab={()=>onNavigateToTab("codelab")}/><div className="mt-5"><h3 className="text-sm font-bold">版本历史</h3><div className="mt-2 flex flex-wrap gap-2">{versions.map(v=><button key={String(v.version)} onClick={()=>void getLearningResource(selected.id,Number(v.version)).then(setSelected)} className="rounded-lg bg-slate-100 px-2 py-1 text-xs">V{String(v.version)} · {String((v.review as {score?:number})?.score??"")}分</button>)}</div></div></>:<div className="flex h-full min-h-96 items-center justify-center text-center text-sm text-slate-400">选择或生成一种真实资源后在此预览</div>}</main></div></div>;
}
