import {lazy,Suspense,useEffect,useState} from 'react';import {AuthProvider,useAuth} from './auth/AuthContext';import {RequireTeacher} from './auth/RequireTeacher';import ChunkErrorBoundary from './components/ChunkErrorBoundary';import {Layout} from './components/Layout';import {navigate} from './router';import {LoginPage} from './pages/LoginPage';
const DashboardPage=lazy(()=>import('./pages/DashboardPage').then(module=>({default:module.DashboardPage})));
const StudentsPage=lazy(()=>import('./pages/StudentsPage').then(module=>({default:module.StudentsPage})));
const StudentDetailPage=lazy(()=>import('./pages/StudentDetailPage').then(module=>({default:module.StudentDetailPage})));
const ClassesPage=lazy(()=>import('./pages/ClassesPage').then(module=>({default:module.ClassesPage})));
const ClassAnalyticsPage=lazy(()=>import('./pages/ClassAnalyticsPage').then(module=>({default:module.ClassAnalyticsPage})));
const ResourcesPage=lazy(()=>import('./pages/ResourcesPage').then(module=>({default:module.ResourcesPage})));
const QuizAnalyticsPage=lazy(()=>import('./pages/QuizAnalyticsPage').then(module=>({default:module.QuizAnalyticsPage})));
const ReportsPage=lazy(()=>import('./pages/ReportsPage').then(module=>({default:module.ReportsPage})));
const ReportDetailPage=lazy(()=>import('./pages/ReportsPage').then(module=>({default:module.ReportDetailPage})));
const AgentLogsPage=lazy(()=>import('./pages/AgentLogsPage').then(module=>({default:module.AgentLogsPage})));
export default function App(){return<AuthProvider><Routes/></AuthProvider>}
function Routes(){const[path,setPath]=useState(window.location.pathname),{user,loading}=useAuth();useEffect(()=>{const change=()=>setPath(window.location.pathname);window.addEventListener('popstate',change);return()=>window.removeEventListener('popstate',change)},[]);useEffect(()=>{if(!loading&&path==='/' )navigate(user&&['TEACHER','ADMIN'].includes(user.role)?'/dashboard':'/login',true);if(!loading&&path==='/login'&&user&&['TEACHER','ADMIN'].includes(user.role))navigate('/dashboard',true)},[loading,path,user]);if(path==='/' )return null;if(path==='/login')return<LoginPage/>;let page:React.ReactNode;if(path==='/dashboard')page=<DashboardPage/>;else if(path==='/students')page=<StudentsPage/>;else if(/^\/students\/\d+$/.test(path))page=<StudentDetailPage studentId={Number(path.split('/')[2])}/>;else if(path==='/classes')page=<ClassesPage/>;else if(/^\/classes\/\d+\/analytics$/.test(path))page=<ClassAnalyticsPage classId={Number(path.split('/')[2])}/>;else if(path==='/resources')page=<ResourcesPage/>;else if(path==='/quizzes')page=<QuizAnalyticsPage/>;else if(path==='/reports')page=<ReportsPage/>;else if(/^\/reports\/\d+$/.test(path))page=<ReportDetailPage reportId={Number(path.split('/')[2])}/>;else if(path==='/agent-logs')page=<AgentLogsPage/>;else page=<div className="rounded-2xl border bg-white p-10 text-center">页面不存在</div>;return<RequireTeacher><Layout path={path}><ChunkErrorBoundary resetKey={path}><Suspense fallback={<div className="rounded-2xl border bg-white p-10 text-center text-sm text-slate-500">正在加载页面…</div>}>{page}</Suspense></ChunkErrorBoundary></Layout></RequireTeacher>}
